#!/bin/sh
# Auto-bump minor version in frontend/package.json on every commit
node -e "
const fs = require('fs');
const path = 'frontend/package.json';
const pkg = JSON.parse(fs.readFileSync(path, 'utf8'));
const [major, minor, patch] = pkg.version.split('.').map(Number);
pkg.version = \`\${major}.\${minor + 1}.\${patch}\`;
fs.writeFileSync(path, JSON.stringify(pkg, null, 2) + '\n');
console.log('Version bumped to ' + pkg.version);
"
git add frontend/package.json
