# Generated by Django 3.1.14 on 2026-02-03 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_auto_20260203_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('seniority_level', models.CharField(blank=True, max_length=50)),
                ('background', models.TextField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('motivations', models.JSONField(blank=True, default=list)),
                ('decision_criteria', models.JSONField(blank=True, default=list)),
                ('preferred_communication', models.CharField(blank=True, max_length=100)),
                ('objections', models.JSONField(blank=True, default=list)),
                ('content_preferences', models.JSONField(blank=True, default=list)),
                ('key_messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='research.researchjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnePager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('executive_summary', models.TextField()),
                ('challenge_section', models.TextField()),
                ('solution_section', models.TextField()),
                ('benefits_section', models.TextField()),
                ('differentiators', models.JSONField(blank=True, default=list)),
                ('call_to_action', models.TextField(blank=True)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('html_content', models.TextField(blank=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('shared', 'Shared')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_pagers', to='research.researchjob')),
            ],
            options={
                'verbose_name_plural': 'One pagers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_type', models.CharField(choices=[('news', 'News Article'), ('website', 'Company Website'), ('report', 'Industry Report'), ('social', 'Social Media'), ('financial', 'Financial Filing'), ('press_release', 'Press Release'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('relevance_note', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='research.researchjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('executive_summary', models.TextField()),
                ('account_overview', models.TextField()),
                ('strategic_objectives', models.JSONField(blank=True, default=list)),
                ('key_stakeholders', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('competitive_landscape', models.TextField(blank=True)),
                ('swot_analysis', models.JSONField(blank=True, default=dict)),
                ('engagement_strategy', models.TextField(blank=True)),
                ('value_propositions', models.JSONField(blank=True, default=list)),
                ('action_plan', models.JSONField(blank=True, default=list)),
                ('success_metrics', models.JSONField(blank=True, default=list)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('timeline', models.TextField(blank=True)),
                ('html_content', models.TextField(blank=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('active', 'Active')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_plan', to='research.researchjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
