# Generated by Django 6.0.1 on 2026-03-23 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('research', '0008_add_current_step_to_researchjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='workproduct',
            name='research_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_products', to='research.researchjob'),
        ),
        migrations.AlterField(
            model_name='workproduct',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_products', to='projects.project'),
        ),
    ]
