# Generated by Django 6.0.1 on 2026-03-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0002_workproduct_nullable_project_add_research_job'),
        ('research', '0008_add_current_step_to_researchjob'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workproduct',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('research_job__isnull', False), _connector='OR'), name='workproduct_has_project_or_research_job'),
        ),
    ]
