# Generated by Django 3.1.14 on 2026-02-03 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_auto_20260203_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('business_problem', models.TextField(help_text='The business problem this addresses')),
                ('proposed_solution', models.TextField(help_text='AI/technology solution overview')),
                ('expected_benefits', models.JSONField(blank=True, default=list)),
                ('estimated_roi', models.CharField(blank=True, max_length=100)),
                ('time_to_value', models.CharField(blank=True, max_length=100)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('data_requirements', models.JSONField(blank=True, default=list)),
                ('integration_points', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('impact_score', models.FloatField(default=0.0)),
                ('feasibility_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('refined', 'Refined'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='research.researchjob')),
            ],
            options={
                'ordering': ['-priority', '-impact_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefinedPlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('elevator_pitch', models.TextField(help_text='30-second pitch')),
                ('value_proposition', models.TextField()),
                ('key_differentiators', models.JSONField(blank=True, default=list)),
                ('target_persona', models.CharField(blank=True, max_length=255)),
                ('target_vertical', models.CharField(blank=True, max_length=100)),
                ('company_size_fit', models.CharField(blank=True, max_length=100)),
                ('discovery_questions', models.JSONField(blank=True, default=list)),
                ('objection_handlers', models.JSONField(blank=True, default=list)),
                ('proof_points', models.JSONField(blank=True, default=list)),
                ('competitive_positioning', models.TextField(blank=True)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('success_metrics', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refined_play', to='ideation.usecase')),
            ],
            options={
                'verbose_name_plural': 'Refined plays',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeasibilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_feasibility', models.CharField(choices=[('low', 'Low - Significant challenges'), ('medium', 'Medium - Some challenges'), ('high', 'High - Readily achievable')], default='medium', max_length=20)),
                ('overall_score', models.FloatField(default=0.0)),
                ('technical_complexity', models.TextField(blank=True)),
                ('data_availability', models.TextField(blank=True)),
                ('integration_complexity', models.TextField(blank=True)),
                ('scalability_considerations', models.TextField(blank=True)),
                ('technical_risks', models.JSONField(blank=True, default=list)),
                ('mitigation_strategies', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_assessment', to='ideation.usecase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
