# Generated by Django 3.1.14 on 2026-02-03 01:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchjob',
            name='vertical',
            field=models.CharField(blank=True, choices=[('healthcare', 'Healthcare'), ('finance', 'Finance'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('energy', 'Energy'), ('telecommunications', 'Telecommunications'), ('media_entertainment', 'Media Entertainment'), ('transportation', 'Transportation'), ('real_estate', 'Real Estate'), ('professional_services', 'Professional Services'), ('education', 'Education'), ('government', 'Government'), ('hospitality', 'Hospitality'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_overview', models.TextField(blank=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('employee_count', models.CharField(blank=True, max_length=100)),
                ('annual_revenue', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('recent_news', models.JSONField(blank=True, default=list)),
                ('decision_makers', models.JSONField(blank=True, default=list)),
                ('pain_points', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('digital_maturity', models.CharField(blank=True, choices=[('nascent', 'Nascent'), ('developing', 'Developing'), ('maturing', 'Maturing'), ('advanced', 'Advanced'), ('leading', 'Leading')], max_length=20)),
                ('ai_footprint', models.TextField(blank=True)),
                ('ai_adoption_stage', models.CharField(blank=True, choices=[('exploring', 'Exploring'), ('experimenting', 'Experimenting'), ('implementing', 'Implementing'), ('scaling', 'Scaling'), ('optimizing', 'Optimizing')], max_length=20)),
                ('strategic_goals', models.JSONField(blank=True, default=list)),
                ('key_initiatives', models.JSONField(blank=True, default=list)),
                ('talking_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='research.researchjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technology_gaps', models.JSONField(blank=True, default=list)),
                ('capability_gaps', models.JSONField(blank=True, default=list)),
                ('process_gaps', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('priority_areas', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analysis_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gap_analysis', to='research.researchjob')),
            ],
            options={
                'verbose_name_plural': 'Gap analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorCaseStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competitor_name', models.CharField(max_length=255)),
                ('vertical', models.CharField(blank=True, choices=[('healthcare', 'Healthcare'), ('finance', 'Finance'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('technology', 'Technology'), ('energy', 'Energy'), ('telecommunications', 'Telecommunications'), ('media_entertainment', 'Media Entertainment'), ('transportation', 'Transportation'), ('real_estate', 'Real Estate'), ('professional_services', 'Professional Services'), ('education', 'Education'), ('government', 'Government'), ('hospitality', 'Hospitality'), ('agriculture', 'Agriculture'), ('construction', 'Construction'), ('nonprofit', 'Nonprofit'), ('other', 'Other')], max_length=50)),
                ('case_study_title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('technologies_used', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_case_studies', to='research.researchjob')),
            ],
            options={
                'verbose_name_plural': 'Competitor case studies',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
    ]
