# Generated by Django 3.1.14 on 2026-02-03 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('research', '0002_auto_20260203_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchjob',
            name='iteration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_job', to='projects.iteration'),
        ),
    ]
