# Generated by Django 3.1.14 on 2026-02-05 16:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchjob_iteration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalOpsIntel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_sentiment', models.JSONField(blank=True, default=dict)),
                ('linkedin_presence', models.JSONField(blank=True, default=dict)),
                ('social_media_mentions', models.JSONField(blank=True, default=list)),
                ('job_postings', models.JSONField(blank=True, default=dict)),
                ('news_sentiment', models.JSONField(blank=True, default=dict)),
                ('key_insights', models.JSONField(blank=True, default=list)),
                ('gap_correlations', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('data_freshness', models.CharField(blank=True, max_length=50)),
                ('analysis_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_ops', to='research.researchjob')),
            ],
            options={
                'verbose_name': 'Internal Operations Intelligence',
                'verbose_name_plural': 'Internal Operations Intelligence',
                'ordering': ['-created_at'],
            },
        ),
    ]
