# Generated by Django 6.0.1 on 2026-03-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_fix_competitor_source_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchjob',
            name='current_step',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
