# Generated by Django 6.0.1 on 2026-03-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_add_current_step_to_researchjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchreport',
            name='synthesis_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='researchjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
