# Generated by Django 6.0.1 on 2026-05-04 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0009_add_partial_status_and_synthesis_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('primary_domain', models.CharField(max_length=255)),
                ('additional_domains', models.JSONField(default=list)),
                ('engagement_context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('phase1_research', 'Phase 1: Web Research'), ('phase1_complete', 'Phase 1 Complete'), ('phase2_auto', 'Phase 2: Automated DNS'), ('awaiting_terminal_output', 'Awaiting Terminal Output'), ('phase2_processing', 'Phase 2: Processing DNS'), ('awaiting_screenshots', 'Awaiting Screenshots'), ('phase3_processing', 'Phase 3: Processing Screenshots'), ('phase4_analysis', 'Phase 4: Analysis'), ('phase5_report', 'Phase 5: Report Generation'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('current_step', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('phase1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase4_completed_at', models.DateTimeField(blank=True, null=True)),
                ('phase5_completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, upload_to='osint_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osint_jobs', to='research.researchjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('infra_type', models.CharField(choices=[('cloud_provider', 'Cloud Provider'), ('cdn', 'CDN'), ('data_center', 'Data Center'), ('colo', 'Colocation'), ('isp', 'ISP'), ('vpn_gateway', 'VPN Gateway'), ('email_provider', 'Email Provider'), ('dns_provider', 'DNS Provider'), ('waf', 'WAF')], max_length=30)),
                ('provider_name', models.CharField(max_length=255)),
                ('evidence', models.TextField()),
                ('ip_ranges', models.JSONField(default=list)),
                ('associated_domains', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_notes', models.TextField(blank=True)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infra_findings', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSecurityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('has_spf', models.BooleanField(default=False)),
                ('spf_record', models.TextField(blank=True)),
                ('spf_assessment', models.CharField(blank=True, max_length=50)),
                ('has_dkim', models.BooleanField(null=True)),
                ('has_dmarc', models.BooleanField(default=False)),
                ('dmarc_record', models.TextField(blank=True)),
                ('dmarc_policy', models.CharField(blank=True, max_length=20)),
                ('mx_providers', models.JSONField(default=list)),
                ('overall_grade', models.CharField(blank=True, max_length=5)),
                ('risk_summary', models.TextField(blank=True)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_assessments', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='DnsFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('MX', 'MX'), ('TXT', 'TXT'), ('NS', 'NS'), ('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('SOA', 'SOA'), ('DMARC', 'DMARC'), ('SPF', 'SPF'), ('PTR', 'PTR')], max_length=10)),
                ('record_value', models.TextField()),
                ('analysis', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_findings', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('dnsdumpster', 'DNSDumpster'), ('shodan', 'Shodan'), ('other', 'Other')], max_length=30)),
                ('image', models.ImageField(upload_to='osint_screenshots/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('analysis', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('mdr_soc', 'MDR / SOC'), ('pen_test', 'Pen Test'), ('vciso_grc', 'vCISO / GRC'), ('ir_retainer', 'IR Retainer'), ('infrastructure', 'Infrastructure'), ('digital_workplace', 'Digital Workplace'), ('app_modernization', 'App Modernization'), ('ai_ops', 'AI Ops'), ('field_cto', 'Field CTO')], max_length=30)),
                ('finding_summary', models.TextField()),
                ('urgency', models.CharField(max_length=20)),
                ('justification', models.TextField()),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='SubdomainFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=50)),
                ('resolves_to', models.GenericIPAddressField(blank=True, null=True)),
                ('is_alive', models.BooleanField(null=True)),
                ('category', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('dev', 'Development'), ('vpn', 'VPN'), ('mail', 'Mail'), ('admin', 'Admin'), ('api', 'API'), ('cdn', 'CDN'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('risk_notes', models.TextField(blank=True)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_findings', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='TerminalSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('dig', 'dig'), ('whois', 'whois'), ('curl', 'curl'), ('nslookup', 'nslookup'), ('arin', 'ARIN'), ('other', 'Other')], max_length=20)),
                ('command_text', models.TextField()),
                ('output_text', models.TextField()),
                ('parsed_data', models.JSONField(default=dict)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_submissions', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='WhoisRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('registrant_name', models.CharField(blank=True, max_length=255)),
                ('registrant_org', models.CharField(blank=True, max_length=255)),
                ('registrar', models.CharField(blank=True, max_length=255)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('name_servers', models.JSONField(default=list)),
                ('raw_whois', models.TextField(blank=True)),
                ('risk_notes', models.TextField(blank=True)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whois_records', to='osint.osintjob')),
            ],
        ),
        migrations.CreateModel(
            name='OsintCommandRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('commands', models.JSONField(default=list)),
                ('rationale', models.TextField(blank=True)),
                ('output_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_rounds', to='osint.osintjob')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('osint_job', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='OsintReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('cover', 'Cover'), ('executive_summary', 'Executive Summary'), ('remediation_plan', 'Remediation Plan'), ('security_roadmap', 'Security Roadmap'), ('entity_findings', 'Entity Findings'), ('regulatory_landscape', 'Regulatory Landscape'), ('engagement_proposal', 'Engagement Proposal'), ('methodology', 'Methodology'), ('infrastructure_maps', 'Infrastructure Maps')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('structured_data', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('osint_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sections', to='osint.osintjob')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('osint_job', 'section_type')},
            },
        ),
    ]
