# Generated by Django 3.1.14 on 2026-02-03 01:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('key_contacts', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('vector_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('research_insight', 'Research Insight'), ('client_interaction', 'Client Interaction'), ('deal_outcome', 'Deal Outcome'), ('best_practice', 'Best Practice'), ('lesson_learned', 'Lesson Learned')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('vector_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Memory entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesPlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('play_type', models.CharField(choices=[('pitch', 'Pitch'), ('objection_handler', 'Objection Handler'), ('value_proposition', 'Value Proposition'), ('case_study', 'Case Study'), ('competitive_response', 'Competitive Response'), ('discovery_question', 'Discovery Question')], max_length=50)),
                ('content', models.TextField()),
                ('context', models.TextField(blank=True, help_text='When to use this play')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('vertical', models.CharField(blank=True, max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('vector_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sales plays',
                'ordering': ['-success_rate', '-usage_count'],
            },
        ),
    ]
